#!/usr/bin/perl

use strict;
use warnings;

my $seq = shift @ARGV;

$\ = "\n";
while( 1 ) {
    my $length = int( rand() *   length( $seq ) + 1 );
    my $start  = int( rand() * ( length( $seq ) - $length + 1 ) );
    print substr $seq, $start, $length;
}
